package com.food.delivery.driverservice.dto;
import lombok.Data;
@Data
public class LocationRequest {
    private Double latitude;
    private Double longitude;
    // Timestamp usually generated by server on receipt
}